SocomTrainingPlatform/Controllers/SiteController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
//using RavenSiteSurvey.Data;
using RavenSiteSurvey.Models;
using RavenSiteSurvey.Models.VIewModels;
using GeoJSON.Net;
using GeoJSON.Net.Geometry;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using FullCalendar;
using FullCalendar.Abstract;
using SocomTrainingPlatform.Models;
using Microsoft.AspNetCore.Http;
using SocomTrainingPlatform.Models.DashboardModels.DashboardViewModels;
using SocomTrainingPlatform.Models.SiteModels;
using System.IO;
using SocomTrainingPlatform.Services;
using SocomTrainingPlatform.BuisnessLogic;
using Azure.Search.Documents;
using Azure.Search.Documents.Indexes;
using Microsoft.Extensions.Configuration;
using Azure;
using Microsoft.AspNetCore.Html;
using System.Text;

namespace SocomTrainingPlatform.Controllers
{
    public class SiteController : Controller
    {
        private readonly SocomTrainingPlatformContext _context;
        private readonly SiteSearchLogic searchLogic;

        //private readonly AddFieldsRepo addFields;


        public SiteController(SocomTrainingPlatformContext context)
        {
            _context = context;
            searchLogic = new SiteSearchLogic(context);
        }


        public async Task<IActionResult> Details(int id)
        {

            Location location = await _context.Locations.FirstOrDefaultAsync(m => m.Id == id);
            List<SiteField> siteFields = await _context.SiteFields.Where(f => f.LocationId == id).ToListAsync();
            List<ExcerciseLocation> exLoc = await _context.ExcerciseLocations.Where(e => e.LocationId == id).ToListAsync();
            PocLocation pocLoc = new PocLocation();
            PointOfContact newPoc = new PointOfContact();
            List<LocationNote> noteList = new List<LocationNote>();
            List<Excercise> exList = new List<Excercise>();
            Mou mou = new Mou();
            List<SelectListItem> targetChoices = new();
            List<PointOfContact> pocList = await _context.PointOfContacts.ToListAsync();
            List<Mou> mouList = await _context.Mous.ToListAsync();


            List<FieldImageModel> fieldsImages = new();

            foreach (var item in siteFields)
            {
                List<FieldImage> image = new();
                if (await _context.FieldImages.FirstOrDefaultAsync(i => i.FieldId == item.Id) != null)
                {
                    image = await _context.FieldImages.Where(i => i.FieldId == item.Id).ToListAsync();
                }

                FieldImageModel newModel = new() { Field = item, Images = image };
                fieldsImages.Add(newModel);
            }

            foreach (var item in exLoc)
            {
                exList.Add(await _context.Excercises.FirstOrDefaultAsync(e => e.Id == item.ExcerciseId));
            }

            if (await _context.Mous.FirstOrDefaultAsync(m => m.Id == location.MouId) != null)
            {
                mou = await _context.Mous.FirstOrDefaultAsync(m => m.Id == location.MouId);
            }

            if (await _context.LocationNotes.Where(N => N.LocationId == id).ToListAsync() != null)
            {
                noteList = await _context.LocationNotes.Where(N => N.LocationId == id).ToListAsync();
            }

            if (await _context.PocLocations.FirstOrDefaultAsync(P => P.LocationId == id) != null)
            {
                pocLoc = await _context.PocLocations.FirstOrDefaultAsync(P => P.LocationId == id);
                newPoc = await _context.PointOfContacts.FirstOrDefaultAsync(P => P.Id == pocLoc.PocId);
            }

            if (location == null)
            {
                return NotFound();
            }

            List<SelectListItem> pocSelect = new();

            foreach (var item in pocList)
            {
                pocSelect.Add(new SelectListItem { Text = item.FirstName + " " + item.LastName, Value = item.Id.ToString() });
            }


            string address = location.StreetAddress;
            string city = location.City;
            string state = location.State;
            string zip = location.ZipCode;
            double Lat = location.Latitude.GetValueOrDefault();
            double Lon = location.Longitude.GetValueOrDefault();

            var viewLocations = new DetailsVm
            {
                location = location,
                SiteFields = fieldsImages,
                poc = newPoc,
                note = noteList,
                Excercises = exList,
                mou = mou,
                MouList = mouList,
            };


            ViewData["PocId"] = pocSelect;
            ViewData["MouId"] = new SelectList(_context.Mous, "Id", "Title");
            ViewData["Lat"] = Lat;
            ViewData["Long"] = Lon;
            ViewData["FullAddress"] = address + ", " + city + ", " + state + " " + zip;

            return View(viewLocations);
        }

        [HttpPost]
        public async Task<IActionResult> AddContact(DetailsVm detailsVm, int id)
        {

            if (detailsVm.pocChoice == 1)
            {
                var pointOfContact = new PointOfContact()
                {
                    FirstName = detailsVm.FirstName,
                    LastName = detailsVm.LastName,
                    EmailAddress = detailsVm.EmailAddress,
                    PhoneNumber = detailsVm.PhoneNumber,
                };
                _context.Add(pointOfContact);
                await _context.SaveChangesAsync();

                var contact = await _context.PointOfContacts.FirstOrDefaultAsync(p => p.PhoneNumber == detailsVm.PhoneNumber);

                var pocLo = new PocLocation()
                {
                    PocId = contact.Id,
                    LocationId = id,
                };
                _context.Add(pocLo);

            }
            else if (detailsVm.pocChoice == 2)
            {
                var pocLo = new PocLocation()
                {
                    PocId = detailsVm.PocId,
                    LocationId = id,
                };
                _context.Add(pocLo);
            }

            await _context.SaveChangesAsync();

            return RedirectToAction("Details", new { id = id });
        }

        public async Task<ActionResult> RemovePoc(int id)
        {
            var location = await _context.Locations.FirstOrDefaultAsync(l => l.Id == id);
            var pocLocation = await _context.PocLocations.FirstOrDefaultAsync(f => f.LocationId == location.Id);

            _context.Remove(pocLocation);
            await _context.SaveChangesAsync();

            return RedirectToAction("Details", new { id = id });
        }

        [HttpPost]
        public async Task<IActionResult> AddNote(DetailsVm detailsVm, int id)
        {
            LocationNote locNote = new LocationNote();

            if (detailsVm.NoteSubject != null && detailsVm.locNote != null)
            {
                locNote.Subject = detailsVm.NoteSubject;
                locNote.Body = detailsVm.locNote;
                locNote.Date = DateTime.Now;
                locNote.LocationId = id;
            }

            await _context.LocationNotes.AddAsync(locNote);
            await _context.SaveChangesAsync();

            return RedirectToAction("Details", new { id });
        }

        [HttpPost]
        public async Task<IActionResult> AddImage(DetailsVm detailsVm, int id)
        {
            FieldImage fieldImage = new();

            using (var ms = new MemoryStream())
            {
                detailsVm.ImageData.CopyTo(ms);
                if (detailsVm.ImageField != null)
                {
                    fieldImage.Image = ms.ToArray();
                    fieldImage.Description = detailsVm.ImageDescription;
                    fieldImage.FieldId = detailsVm.FieldId;

                    _context.Add(fieldImage);
                }
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", new { id = id });
        }

        [HttpPost]
        public async Task<IActionResult> AddMou(DetailsVm detailsVm, int id)
        {
            Location location = _context.Locations.FirstOrDefault(l => l.Id == id);

            if (detailsVm.MouId > 0)
            {
                location.MouId = detailsVm.MouId;
                _context.Update(location);
                await _context.SaveChangesAsync();
            };

            return RedirectToAction("Details", new { id = id });
        }

        public async Task<IActionResult> RemoveMou(int id)
        {
            var location = await _context.Locations.FirstOrDefaultAsync(l => l.Id == id);

            location.MouId = null;

            _context.Locations.Update(location);
            await _context.SaveChangesAsync();

            return RedirectToAction("Details", new { id = id });
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddSiteVm locationViewModel)
        {
            Location location = new();

            if (ModelState.IsValid)
            {
                location.Name = locationViewModel.Name;
                location.StreetAddress = locationViewModel.StreetAddress;
                location.City = locationViewModel.City;
                location.State = locationViewModel.State;
                location.ZipCode = locationViewModel.ZipCode;
                location.Latitude = locationViewModel.Latitude;
                location.Longitude = locationViewModel.Longitude;

                _context.Add(location);

            };

            await _context.SaveChangesAsync();

SocomTrainingPlatform/Views/Site/Create.cshtml
@model SocomTrainingPlatform.Models.SiteModels.AddSiteVm


@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/AdminLayout/_Layout.cshtml";
}
<style>
    fieldset[disabled] {
        display: none
    }
</style>
<div class="card card-primary" style="padding-top: 10px">
    <div class="card-body">
       <div class="form-group">
        <h4>Add new site</h4>
      </div>
        <form asp-action="Create" id="createForm" style="background-color: white">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Add Location:</label>
                        <input class="form-control" id="txtLocation" autocomplete="off" />
                    </div>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label asp-for="StreetAddress" class="control-label"></label>
                            <input asp-for="StreetAddress" class="form-control" id="StreetAddress" autocomplete="off" />
                            <span asp-validation-for="StreetAddress" class="text-danger"></span>
                        </div>
                        <div class="col-md-6 form-group">
                            <label asp-for="City" class="control-label"></label>
                            <input asp-for="City" class="form-control" id="City" autocomplete="off" />
                            <span asp-validation-for="City" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label asp-for="State" class="control-label"></label>
                            <input asp-for="State" class="form-control" id="State" autocomplete="off" />
                            <span asp-validation-for="State" class="text-danger"></span>
                        </div>
                        <div class="col-md-6 form-group">
                            <label asp-for="ZipCode" class="control-label"></label>
                            <input asp-for="ZipCode" class="form-control" id="Zip" autocomplete="off" />
                            <span asp-validation-for="ZipCode" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label asp-for="Latitude" class="control-label"></label>
                            <input asp-for="Latitude" class="form-control" id="Latitude" autocomplete="off" />
                            <span asp-validation-for="Latitude" class="text-danger"></span>
                        </div>
                        <div class="col-md-6 form-group">
                            <label asp-for="Longitude" class="control-label"></label>
                            <input asp-for="Longitude" class="form-control" id="Longitude" autocomplete="off" />
                            <span asp-validation-for="Longitude" class="text-danger"></span>
                        </div>
                    </div>
@*                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label asp-for="Grid" class="control-label"></label>
                            <input asp-for="Grid" class="form-control" />
                            <span asp-validation-for="Grid" class="text-danger"></span>
                        </div>
                        <div class="col-md-6 form-group">
                            <div class="form-group">
                                <label for="exampleInputFile">Mou</label>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="exampleInputFile">
                                        <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                                    </div>
                                    <div class="input-group-append">
                                        <span class="input-group-text">Upload</span>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label asp-for="MouStartDate" class="control-label"></label>
                            <input asp-for="MouStartDate" class="form-control" />
                            <span asp-validation-for="MouStartDate" class="text-danger"></span>
                        </div>
                        <div class="col-md-6 form-group">
                            <label asp-for="MouEndDate" class="control-label"></label>
                            <input asp-for="MouEndDate" class="form-control" />
                            <span asp-validation-for="MouEndDate" class="text-danger"></span>
                        </div>
                    </div>*@
                        </div>
                        </div>
            <div class="form-group">
                <input type="submit" asp-action="Create" asp-controller="Site" value="Create" class="btn btn-primary" id="btnSubmit" onclick="return stopMultipleSubmit();"/>
            </div>
        </form>
    </div>
</div>

<div class="container-fluid">
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
<script src="~/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false&libraries=places&key=AIzaSyDlAbZMZiUy1x15UbJfvZwg1zi6TNIh764"></script>
<script type="text/javascript">    google.maps.event.addDomListener(window, 'load', function () {
                var options = { componentRestrictions: { country: "us" } };
                var places = new google.maps.places.Autocomplete(document.getElementById('txtLocation'), options);
                google.maps.event.addListener(places, 'place_changed', function () {
                    var address = '';
                    var route = '';
                    var postcode = '';
                    var locality = '';
                    var state = '';
                    var country = '';
                    var place = places.getPlace();
                    var latitude = places.getPlace().geometry.location.lat();
                    var longitude = places.getPlace().geometry.location.lng();;
                    var AddressComponents = places.getPlace().address_components;
                    for (var i = 0; i < AddressComponents.length; i++) {
                        var componentType = AddressComponents[i].types[0];
                        switch (componentType) {
                            //For Street Number
                            case "street_number": {
                                address = `${AddressComponents[i].long_name} ${address}`;
                                break;
                            }
                            //For Address

                            case "route": {
                                route = AddressComponents[i].short_name;
                                break;
                            }
                            //For PinCode
                            case "postal_code": {
                                postcode = `${AddressComponents[i].long_name}${postcode}`;
                                break;
                            }
                            //For PinCode
                            case "postal_code_prefix": {
                                if (postcode == '') {
                                    postcode = AddressComponents[i].long_name;
                                }
                                break;
                            }
                            //For City

                            case "locality": {
                                locality = AddressComponents[i].long_name;
                                break;
                            }
                            //For City
                            case "administrative_area_level_2": {
                                if (locality == '') {
                                    locality = AddressComponents[i].long_name;
                                }
                                break;
                            }
                            //For State
                            case "administrative_area_level_1": {
                                state = AddressComponents[i].short_name;
                                break;
                            }
                            //For Country

                            case "country": {
                                country = AddressComponents[i].long_name;
                                break;
                            }
                        }
                    }

                    $('#StreetAddress').val(address + " " + route);
                    $('#City').val(locality);
                    $('#State').val(state);
                    //$('#txtCountry').val(country);
                    $('#Zip').val(postcode);
                    $('#Latitude').val(latitude);
                    $('#Longitude').val(longitude);


                });

            });</script>

    @if (ViewBag.Message != null)
    {
<script type="text/javascript">
    window.onload = function(){
        alert("@ViewBag.Message");
</script>
    };
<script>
        $("createForm").submit(function (e) { // 'e' <- add this line of code
            e.preventDefault(); // <- add this line of code
            if ($(this).valid()) {
                $(this).find(":submit").attr("disabled", "disabled");
            }
        });
</script>
<script>
        var isSubmitted = false;
                    function stopMultipleSubmit() {
                        if (!isSubmitted) {
                            $('#btnSubmit').val('Submitting.. Please Wait..');
                            $("#btnSubmit").prop('disabled', true);
                            isSubmitted = true;
                            $("#btnSubmit").submit();
                            return true;
                        }
                        else {
                            return false;
                        }
                    }
                }        
</script>

<script>
        (function () {
    //Initialize Select2 Elements
         $('.select2').select2()
         })
         (function () {
             $('Select2').select2('data');
         })
</script>
<script>
    $("#choice").change(function(){
  $("#A,#B,#C,#D,#E").hide();
  if($(this).val() == "A"){
    $("#A").show();
  }
  else if($(this).val() == "B"){
    $("#B").show();
  }
  else if($(this).val() == "C"){
    $("#C").show();
  }
  else if($(this).val() == "D"){
    $("#D").show();
  }
  else if($(this).val() == "E"){
    $("#E").show();
  }
});

</script>
}

SocomTrainingPlatform/Views/Site/DeleteSite.cshtml
@model SocomTrainingPlatform.Models.Location

@{
    ViewData["Title"] = "Delete";
}

<h3>Are you sure you want to delete this Site?</h3>
<div>
    <h4>Mou</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StreetAddress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StreetAddress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ZipCode)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Latitude)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Longitude)
        </dd>
    </dl>

    <form asp-action="DeleteSite">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Details" asp-route-id="@Model.Id">Back to Site Details</a>
    </form>
</div>

SocomTrainingPlatform/Views/Site/DeleteSiteField.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

SocomTrainingPlatform/Views/Site/EditSiteField.cshtml
@model SocomTrainingPlatform.Models.SiteField

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Site Field</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditSiteField">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="LocationId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Choose field type</label>
                <div>
                    <select class="form-control" asp-for="Field" id="choice" style="width: 100%;">
                        <option selected="selected" id="choose">Choose...</option>
                        <option value="Target">Target</option>
                        <option value="Support">Support</option>
                        <option value="InsertPoint">Insert Points</option>
                        <option value="Berthing">Berthing/Work</option>
                        <option value="Meeting">Meeting</option>
                    </select>
                </div>
                <hr />
                <div id="allChoices">
                    <div class="form-group" id="Target" style="display: none;">
                        <select id="aa" class="form-control" asp-for="Type" style="width: 100%;">
                            <option selected="selected">Choose...</option>
                            <option value="DA/Raid">DA/Raid</option>
                            <option value="R&S">R&S</option>
                            <option value="VehicleIntrediction">Vehicle Intrediction</option>
                            <option value="Ambush">Ambush</option>
                            <option value="RAA">RAA</option>
                            <option value="VirtualSynthetic">Virtual/Synthetic</option>
                            <option value="Gaf">GAF</option>
                            <option value="Haf">HAF</option>
                            <option value="Baf">Baf</option>
                        </select>
                    </div>
                    <div class="form-group" id="Support" style="display: none;">
                        <select id="bb" class="form-control" asp-for="Type" style="width: 100%;">
                            <option selected="selected">Choose...</option>
                            <option value="MotorPool">Motor Pool</option>
                            <option value="FuelFarm">Fuel Farm</option>
                            <option value="Contractor">Contractor</option>
                            <option value="MedicalFacility">Medical Facility</option>
                        </select>
                    </div>
                    <div class="form-group" id="InsertPoint" style="display: none;">
                        <select id="cc" class="form-control" asp-for="Type" style="width: 100%;">
                            <option selected="selected">Choose...</option>
                            <option value="Airfield/Runway">Airfield/Runway</option>
                            <option value="DZ">DZ</option>
                            <option value="HLZ">HLZ</option>
                            <option value="SplashPoint">SplashPoint</option>
                            <option value="VDO/Lagger">VDO/Lagger</option>
                        </select>
                    </div>
                    <div class="form-group" id="Berthing" style="display: none;">
                        <select id="dd" class="form-control" asp-for="Type" style="width: 100%;">
                            <option selected="selected">Choose...</option>
                            <option value="ECG">ECG</option>
                            <option value="SOTF/HHQ">SOTF/HHQ</option>
                            <option value="Company">Company</option>
                            <option value="TeamSite">Team Site</option>
                        </select>
                    </div>
                    <div class="form-group" id="Meeting" style="display: none;">
                        <select id="ee" class="form-control" asp-for="Type" style="width: 100%;">
                            <option selected="selected">Choose...</option>
                            <option value="SA">SA</option>
                            <option value="KLE">KLE</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Grid" class="control-label"></label>
                <input asp-for="Grid" class="form-control" />
                <span asp-validation-for="Grid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



<div>
    <a asp-action="Details" asp-route-id="@Model.LocationId">Back to Site</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        $("#choice").change(function () {
            $("#aa,#bb,#cc,#dd,#ee").val([]);
            $("#Target,#Support,#InsertPoint,#Berthing,#Meeting").hide();

            if ($(this).val() == "Target") {
                $("#Target").show();
            }
            else if ($(this).val() == "Support") {
                $("#Support").show();
            }
            else if ($(this).val() == "InsertPoint") {
                $("#InsertPoint").show();
            }
            else if ($(this).val() == "Berthing") {
                $("#Berthing").show();
            }
            else if ($(this).val() == "Meeting") {
                $("#Meeting").show();
            }
        });

    </script>
<script>
    $(document).ready(function () {
        var field = @Model.Field;
        var type = @Model.Type;

        if ($(field).val() == "Target") {
            $("#Target").show();
            $("#aa").val(type);
        }
        else if ($(field).val() == "Support") {
            $("#Support").show();
            $("#bb").val(type);
        }
        else if ($(field).val() == "InsertPoint") {
            $("#InsertPoint").show();
            $("#cc").val(type);
        }
        else if ($(field).val() == "Berthing") {
            $("#Berthing").show();
            $("#dd").val(type);
        }
        else if ($(field).val() == "Meeting") {
            $("#Meeting").show();
            $("#dd").val(type);
        }

    });
</script>
}